name: audit

on:
  workflow_call:
    inputs:
      audit-ci-directory:
        type: string
        description: The directory containing the package.json to audit
        required: false
        default: ./

jobs:
  audit_ci:
    runs-on: ubuntu-latest
    name: Audit NPM dependencies
    timeout-minutes: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Audit NPM dependencies
        run: npx audit-ci --low --directory=${{ inputs.audit-ci-directory }}

  sensiolabs_security_checker:
    runs-on: ubuntu-latest
    name: Audit Composer dependencies
    timeout-minutes: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup cache
        uses: actions/cache@v2
        id: cache-db
        with:
          path: ~/.symfony/cache
          key: db

      - name: Audit Composer dependencies
        uses: symfonycorp/security-checker-action@v2
