name: audit

on:
  workflow_call:
    inputs:
      node-version:
        description: Node version to use for running audit-ci
        required: false
        type: string
        default: 14

jobs:
  audit_ci:
    runs-on: ubuntu-latest
    name: Audit NPM dependencies
    timeout-minutes: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ inputs.node-version }}

      - name: Audit NPM dependencies
        run: npx audit-ci --moderate

  sensiolabs_security_checker:
    runs-on: ubuntu-latest
    name: Audit Composer dependencies
    timeout-minutes: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup cache
        uses: actions/cache@v2
        id: cache-db
        with:
          path: ~/.symfony/cache
          key: db

      - name: Audit Composer dependencies
        uses: symfonycorp/security-checker-action@v2
