name: code-style

on:
  workflow_call:
    inputs:
      fix:
        required: false
        type: boolean
        default: false
      php-version:
        description: PHP version to use for running PHP_CodeSniffer
        required: false
        type: string
        default: 8.0
      php-extensions:
        description: Comma-separated list of PHP extensions to install
        required: false
        type: string
    secrets:
      composer-auth:
        required: false

jobs:
  phpcs:
    runs-on: ubuntu-latest
    name: PHP_CodeSniffer
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          extensions: ${{ inputs.php-extensions }}
          tools: composer:v2, cs2pr

      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Setup Composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
        env:
          COMPOSER_AUTH: ${{ secrets.composer-auth }}

      - name: Run PHPCBF
        if: ${{ github.event_name == 'pull_request' && inputs.fix }}
        continue-on-error: true
        run: vendor/bin/phpcbf

      - name: Commit PHPCBF fixes
        if: ${{ github.event_name == 'pull_request' }}
        uses: EndBug/add-and-commit@v8
        with:
          message: Apply fixes from `phpcbf`
          commit: --no-verify
          push: origin --set-upstream --no-verify
          committer_name: GitHub Actions
          committer_email: actions@github.com

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs --report=checkstyle -q | cs2pr --graceful-warnings
