name: phpstan

on:
  workflow_call:
    inputs:
      php-version:
        description: PHP version to use for running PHPStan
        required: false
        type: string
        default: 8.0
      php-extensions:
        description: Comma-separated list of PHP extensions to install
        required: false
        type: string
    secrets:
      composer-auth:
        required: false

jobs:
  phpstan:
    runs-on: ubuntu-latest
    name: PHPStan Analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          extensions: ${{ inputs.php-extensions }}
          tools: composer:v2

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --no-scripts
        env:
          COMPOSER_AUTH: ${{ secrets.composer-auth }}

      - name: Run PHPStan
        run: vendor/bin/phpstan --no-progress
